(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (ws-butler winum volatile-highlights vi-tilde-fringe uuidgen symon string-inflection spaceline-all-the-icons spaceline powerline restart-emacs request rainbow-delimiters popwin persp-mode password-generator paradox spinner org-projectile org-category-capture open-junk-file neotree move-text lorem-ipsum link-hint ivy-purpose window-purpose imenu-list indent-guide hungry-delete hl-todo highlight-parentheses highlight-numbers parent-mode highlight-indentation google-translate golden-ratio flx-ido fill-column-indicator fancy-battery eyebrowse expand-region evil-visualstar evil-visual-mark-mode evil-unimpaired evil-tutor evil-surround evil-numbers evil-nerd-commenter evil-matchit evil-lisp-state evil-lion evil-indent-plus evil-iedit-state iedit evil-goggles evil-exchange evil-escape evil-ediff evil-cleverparens smartparens paredit evil-args evil-anzu anzu eval-sexp-fu highlight editorconfig dumb-jump doom-modeline eldoc-eval shrink-path define-word counsel-projectile column-enforce-mode clean-aindent-mode centered-cursor-mode auto-highlight-symbol aggressive-indent ace-window ace-link avy font-lock+ youdao-dictionary yasnippet-snippets yapfify xterm-color which-key wgrep web-mode web-beautify vimrc-mode use-package unfill toml-mode toc-org tagedit smex smeargle slim-mode shell-pop scss-mode sass-mode rainbow-mode rainbow-identifiers racer pyvenv pytest pyim pyenv-mode py-isort pug-mode prettier-js pippel pipenv pip-requirements pcre2el overseer orgit organic-green-theme org-present org-pomodoro org-mime org-download org-bullets org-brain oldlace-theme nameless mwim multi-term mmm-mode markdown-toc magit-svn magit-gitflow macrostep livid-mode live-py-mode json-navigator json-mode js2-refactor js-doc ivy-yasnippet ivy-xref ivy-rtags ivy-hydra importmagic impatient-mode helm-make google-c-style gnuplot gitignore-templates gitignore-mode gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link git-gutter-fringe git-gutter-fringe+ gh-md fuzzy flyspell-correct-ivy flycheck-rust flycheck-rtags flycheck-pos-tip flx evil-org evil-magit eshell-z eshell-prompt-extras esh-help emmet-mode elisp-slime-nav dotenv-mode doom-themes disaster diminish diff-hl dactyl-mode cython-mode counsel-css company-web company-tern company-statistics company-rtags company-c-headers company-auctex company-anaconda color-identifiers-mode clang-format cargo browse-at-remote bind-map auto-yasnippet auto-dictionary auto-compile auctex-latexmk ac-ispell))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
