(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (google-c-style youdao-dictionary yasnippet-snippets yapfify yaml-mode writeroom-mode winum which-key wgrep web-mode web-beautify vimrc-mode uuidgen use-package unfill treemacs-projectile treemacs-magit treemacs-evil toml-mode toc-org tldr tide tagedit symbol-overlay string-inflection ssh-agency spaceline-all-the-icons smex slim-mode sicp scss-mode sass-mode restart-emacs rainbow-mode rainbow-identifiers racer pytest pyim pyenv-mode py-isort pug-mode prettier-js popwin pippel pipenv pip-requirements persp-mode pcre2el password-generator paradox pangu-spacing overseer organic-green-theme org-pomodoro org-plus-contrib org-mime org-cliplink open-junk-file oldlace-theme nodejs-repl nameless mwim mvn move-text mmm-mode meghanada maven-test-mode markdown-toc magit-svn macrostep lsp-ui lsp-treemacs lsp-python-ms lsp-java lsp-haskell live-py-mode link-hint json-snatcher json-reformat json-navigator json-mode js2-refactor js-doc ivy-yasnippet ivy-xref ivy-rtags ivy-hydra intero indent-guide importmagic impatient-mode ibuffer-projectile hybrid-mode hungry-delete hlint-refactor hl-todo hindent highlight-parentheses highlight-numbers haskell-snippets groovy-mode groovy-imports graphviz-dot-mode gradle-mode golden-ratio gnuplot gitignore-templates gitignore-mode gitconfig-mode gitattributes-mode git-timemachine git-messenger git-link ggtags fuzzy font-lock+ flyspell-correct-ivy flycheck-rust flycheck-rtags flycheck-pos-tip flycheck-package flycheck-haskell flx find-by-pinyin-dired fill-column-indicator expand-region exec-path-from-shell evil-visualstar evil-visual-mark-mode evil-tutor evil-textobj-line evil-surround evil-org evil-numbers evil-nerd-commenter evil-matchit evil-magit evil-lion evil-iedit-state evil-goggles evil-escape evil-cleverparens evil-anzu engine-mode emmet-mode elisp-slime-nav editorconfig dumb-jump dotenv-mode doom-themes doom-modeline diminish devdocs dap-mode dante dactyl-mode cython-mode cquery cpp-auto-include counsel-projectile counsel-gtags counsel-css company-web company-statistics company-rtags company-reftex company-lsp company-ghci company-ghc company-cabal company-c-headers company-auctex company-anaconda column-enforce-mode color-identifiers-mode cmm-mode clojure-snippets cider-eval-sexp-fu cider chinese-conv centered-cursor-mode ccls cargo blacken bind-map auto-yasnippet auto-highlight-symbol auto-compile auctex-latexmk attrap aggressive-indent ace-pinyin ace-link))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
